CREATE TABLE `migrations` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
   	`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`resource` VARCHAR(100) NOT NULL,
	`type` VARCHAR(100) NOT NULL,
   	`name` VARCHAR(100) NOT NULL,
	`version` VARCHAR(100) NOT NULL,

	PRIMARY KEY (`id`),
	INDEX `logs_date` (`date`)
);