CREATE TABLE `identifiers` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `steam` VARCHAR(255) NULL DEFAULT NULL,
    `license` VARCHAR(255) NULL DEFAULT NULL,
    `xbl` VARCHAR(255) NULL DEFAULT NULL,
    `live` VARCHAR(255) NULL DEFAULT NULL,
    `discord` VARCHAR(255) NULL DEFAULT NULL,
    `fivem` VARCHAR(255) NULL DEFAULT NULL,
    `ip` VARCHAR(255) NULL DEFAULT NULL,
    `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);